export const StatesArray = [
  { id: "AL", description: "Alabama" },
  { id: "AK", description: "Alaska" },
  { id: "AZ", description: "Arizona" },
  { id: "AR", description: "Arkansas" },
  { id: "CA", description: "California" },
  { id: "CO", description: "Colorado" },
  { id: "DC", description: "District of Columbia" },
  { id: "FL", description: "Florida" },
  { id: "GA", description: "Georgia" },
  { id: "HI", description: "Hawaii" },
  { id: "ID", description: "Idaho" },
  { id: "IL", description: "Illinois" },
  { id: "IN", description: "Indiana" },
  { id: "KS", description: "Kansas" },
  { id: "KY", description: "Kentucky" },
  { id: "LA", description: "Louisiana" },
  { id: "MA", description: "Massachusetts" },
  { id: "MD", description: "Maryland" },
  { id: "ME", description: "Maine" },
  { id: "MI", description: "Michigan" },
  { id: "MN", description: "Minnesota" },
  { id: "MO", description: "Missouri" },
  { id: "MS", description: "Mississippi" },
  { id: "MT", description: "Montana" },
  { id: "NC", description: "North Carolina" },
  { id: "ND", description: "North Dakota" },
  { id: "NE", description: "Nebraska" },
  { id: "NH", description: "New Hampshire" },
  { id: "NJ", description: "New Jersey" },
  { id: "NM", description: "New Mexico" },
  { id: "NV", description: "Nevada" },
  { id: "NY", description: "New York" },
  { id: "OH", description: "Ohio" },
  { id: "OK", description: "Oklahoma" },
  { id: "OR", description: "Oregon" },
  { id: "PA", description: "Pennsylvania" },
  { id: "RI", description: "Rhode Island" },
  { id: "SC", description: "South Carolina" },
  { id: "SD", description: "South Dakota" },
  { id: "TN", description: "Tennessee" },
  { id: "UT", description: "Utah" },
  { id: "VA", description: "Virginia" },
  { id: "VT", description: "Vermont" },
  { id: "WA", description: "Washington" },
  { id: "WI", description: "Wisconsin" },
  { id: "WV", description: "West Virginia" },
  { id: "WY", description: "Wyoming" },
  { id: "PR", description: "Puerto Rico" },
  { id: "VI", description: "U.S. Virgin Islands" },
  { id: "GU", description: "Guam" },
  { id: "MP", description: "Northern Mariana Islands" },
  { id: "AS", description: "American Samoa" },
  { id: "FM", description: "Federated States of Micronesia" },
  { id: "MH", description: "Marshall Islands" },
  { id: "PW", description: "Palau" },
];
